"""empty message

Revision ID: 7c5907f4f1c4
Revises: c07d8032cb31
Create Date: 2023-07-10 20:38:10.007599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5907f4f1c4'
down_revision = 'c07d8032cb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('court_type', sa.String(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('game_type')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_column('court_type')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
