"""empty message

Revision ID: b082a357475c
Revises: 8e2d569d801c
Create Date: 2023-07-14 10:36:29.158977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b082a357475c'
down_revision = '8e2d569d801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_image', sa.String(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('court_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('image')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_image', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('player_image')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('court_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('court_image')

    # ### end Alembic commands ###
