"""added home & away scores to playergames

Revision ID: c07d8032cb31
Revises: 85dcf4acc31c
Create Date: 2023-07-10 14:09:39.988634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07d8032cb31'
down_revision = '85dcf4acc31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_score', sa.Integer(), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('away_score')
        batch_op.drop_column('home_score')

    # ### end Alembic commands ###
